package com.eatplease.app.data

import androidx.room.ConstructedBy
import androidx.room.Database
import androidx.room.RoomDatabase
import androidx.room.RoomDatabaseConstructor

@Database(
    entities = [WatchSession::class, EatingEvent::class],
    version = 1,
    exportSchema = true,
)
@ConstructedBy(EatPleaseDatabaseConstructor::class)
abstract class EatPleaseDatabase : RoomDatabase() {
    abstract fun watchDao(): WatchDao
}

// The actual implementations are generated by the Room compiler per target.
@Suppress("KotlinNoActualForExpect", "EXPECT_ACTUAL_CLASSIFIERS_ARE_IN_BETA_WARNING")
expect object EatPleaseDatabaseConstructor : RoomDatabaseConstructor<EatPleaseDatabase> {
    override fun initialize(): EatPleaseDatabase
}
